### PR TITLE
Add the option to be quiet when running validate.

### PR DESCRIPTION
**Pull request by singularo**

### CODE REVIEW

**Comment by pingers** [comment]
I don't think this is needed.

**Comment by davemikolaj** [comment]
Being quiet omits error messages too - for example you'll miss an error like

`The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update`.`

This means you are relying on exit codes, which still won't tell you exactly what the issue is.

**Comment by singularo** [comment]
Yeah, so thats what I was wondering @davemikolaj but forgot to ask you when we got coffee..

**Comment by singularo** [comment]
Cancelling this then. Its more like a feature request for composer.

**Pull request closed without merging**
