### PR TITLE
Remove the infinispan parts.

### PR DESCRIPTION
**Pull request by singularo**
Removing all the redis stuff for local development.
Leaving in the settings.php until we remove redis from non-prod sites (that could be a while).
Switching to memcache for local dev should highlight any possible memcache related issues better than using redis for local.
Having redis for non-prod sites is a bit icky so we should also switch that to memcache, but those changes need to be made in shepherd.

### CODE REVIEW

**Comment by pingers** [comment]
Looks ready to go for me.

**Comment by singularo** [comment]
Yeah, but need to test with Adams changes, that why no assignees yet ;-)

**Comment by pingers** [comment]
Hmm... probably need to leave redis in our dev setup until we get it out of production.

**Comment by singularo** [comment]
That to had also crossed my mind, after i'd done it.

**Pull request closed without merging**
