### PR TITLE
Don't try to use an invalid cache bin when the redis module and servi…

### PR DESCRIPTION
**Pull request by pingers**
…ces don't exist.

### CODE REVIEW

**Comment by singularo** [comment]
Does this solve the install.php problem @pingers ?
How to reproduce?

**Comment by pingers** [comment]
Don't know yet... pain in the butt to test.

**Comment by pingers** [comment]
I'm seeing: `Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "cache.backend.redis". Did you mean one of these: "cache.backend.apcu", "cache.backend.php", "cache.backend.memory"? in Drupal\Component\DependencyInjection\Container->get() (line 157 of /code/web/core/lib/Drupal/Component/DependencyInjection/Container.php). ` during manual install on openshift though...

**Comment by singularo** [comment]
Yeah, just merge if you need to.

**Pull request closed without merging**
